spring:
  application:
    name: intelligent-meter-reading-system
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:meter-reading-system}
      access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:PT2H}
      refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL:P7D}
      secret-base64: ${JWT_SECRET_BASE64}

server:
  port: ${SERVER_PORT:8070}
