global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    system: intelligent-meter-reading-system
    environment: local

scrape_configs:
  - job_name: meter-reading-api
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:8070
        labels:
          service: meter-api

  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets:
          - rabbitmq:15692
        labels:
          service: rabbitmq
